name: sports
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pandas>1.0.0
  - jupyter
  - numpy
  - matplotlib
  - selenium
  - urllib3
  - seaborn
  - statsmodels
  - scikit-learn
  - scipy
  - pystan
  - gpytorch
  - bs4
  - lxml
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio