name: sports
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas>1.0.0
  - jupyter
  - numpy
  - matplotlib
  - selenium
  - urllib3
  - seaborn
  - statsmodels
  - scikit-learn